language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - SH=bash
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$(pwd/media_parser)
before_script:
  - mongo admin --eval 'db.createUser({user:"run_admin_run",pwd:"run_pass_run",roles:["dbAdminAnyDatabase"]});'
services:
  - mongodb
script:
  - python ./media_parser/insert_media_mongodb.py --port_num=27017
  - python -m pytest
branches:
  only:
   - master
